from dash import html, dcc
from components import header

# This is the layout for the NEW /history page
history_layout = html.Div(className='layout-wrapper', children=[
    header,
    html.Div(className='main-container', children=[
        # This card is wider to accommodate the gauges and table
        html.Div(className='card dashboard-card', children=[
            
            html.H2("Your Debate History"),
            html.P("Select a debate from your history to review the results and transcript."),
            
            # This dropdown will be filled by a callback
            dcc.Dropdown(
                id='history-dropdown',
                placeholder="Select a past debate...",
                clearable=False
            ),
            
            html.Hr(),
            
            # This container's content is generated by a callback
            # when you select a debate from the dropdown.
            html.Div(id='history-content-container'),
            
            # Button to go back home
            html.Button(
                'Back to Home', 
                id='history-back-home-button', 
                n_clicks=0, 
                className='btn btn-secondary', 
                style={'marginTop': '20px'}
            )
        ])
    ])
])