from dash import html, dcc
from components import header

# This is the layout for the JUDGE (Human vs Human) results page
judge_dashboard_layout = html.Div(className='layout-wrapper', children=[
    header,
    html.Div(className='main-container', children=[
        # This card is wider to accommodate the gauges and table
        html.Div(className='card dashboard-card', children=[
            
            # This container's content is generated by the new 
            # 'render_judge_dashboard' callback
            html.Div(id='judge-dashboard-content')
        ])
    ])
])